// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"
#include "winrt/Composable.Base.h"
#include "winrt/Composable.Outer.h"

namespace winrt::Composable::Outer::implementation {

template <typename D, typename ... I>
struct WINRT_EBO Foo_base : impl::module_lock, implements<D, Composable::Outer::IFoo, Composable::Base::IRootOverrides, composing, I ...>,
    impl::require<D, Composable::Base::IRoot>,
    impl::base<D, Composable::Base::Root>,
    Composable::Base::IRootOverridesT<D>
{
    using class_type = Composable::Outer::Foo;
    using composable_base = Composable::Base::Root;
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename D::first_interface, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Composable.Outer.Foo";
    }
    Foo_base()
    {
        get_activation_factory<Composable::Base::Root, Composable::Base::IRootFactory>().CreateInstance(*this, this->m_inner);
    }
};

}

namespace winrt::Composable::Outer::factory_implementation {

template <typename D, typename T, typename ... I>
struct WINRT_EBO FooT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Composable.Outer.Foo";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_FOO_XAML_G_H) || __has_include("Foo.xaml.g.h")

#include "Foo.xaml.g.h"

#else

namespace winrt::Composable::Outer::implementation
{
    template <typename D, typename ... I>
    using FooT = Foo_base<D, I ...>;
}

#endif
