// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "module.h"

namespace winrt {

namespace Farm::Animals::implementation {

template <typename D, typename ... I>
struct EggBase : impl::module_lock, implements<D, Farm::Animals::IEgg, I ...>
{
    using class_type = Farm::Animals::Egg;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Egg";
    }
};

template <typename D, typename T, typename ... I>
struct EggFactoryBase : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Farm::Animals::IEggFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Egg";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Farm::Animals::IEgg CreateWithHen(Farm::Animals::Hen const& mother)
    {
        return make<T>(mother);
    }
};

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_EGG_X_H) || __has_include("Egg.x.h")

#include "Egg.x.h"

#else

template <typename D, typename ... I>
using EggT = EggBase<D, I ...>;

template <typename D, typename T, typename ... I>
using EggFactoryT = EggFactoryBase<D, T, I ...>;

#endif

}

}
