// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"

namespace winrt::Farm::Animals::implementation {

template <typename D, typename ... I>
struct Egg_base : impl::module_lock, implements<D, Farm::Animals::IEgg, I ...>
{
    using class_type = Farm::Animals::Egg;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Egg";
    }
};

}

namespace winrt::Farm::Animals::factory_implementation {

template <typename D, typename T, typename ... I>
struct EggT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Farm::Animals::IEggFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Egg";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Farm::Animals::IEgg CreateWithHen(Farm::Animals::Hen const& mother)
    {
        return make<T>(mother);
    }
};

}

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_EGG_XAML_G_H) || __has_include("Egg.xaml.g.h")

#include "Egg.xaml.g.h"

#else

namespace winrt::Farm::Animals::implementation
{
    template <typename D, typename ... I>
    using EggT = Egg_base<D, I ...>;
}

#endif
