// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"
#include "winrt/Farm.Animals.h"

namespace winrt::Farm::Animals::implementation {

template <typename D, typename ... I>
struct WINRT_EBO Egg_base : impl::module_lock, implements<D, Farm::Animals::IEgg, I ...>
{
    using class_type = Farm::Animals::Egg;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename D::first_interface, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Egg";
    }
};

}

namespace winrt::Farm::Animals::factory_implementation {

template <typename D, typename T, typename ... I>
struct WINRT_EBO EggT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Farm::Animals::IEggFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Egg";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Farm::Animals::IEgg CreateWithHen(Farm::Animals::Hen const& mother)
    {
        return make<T>(mother);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_EGG_XAML_G_H) || __has_include("Egg.xaml.g.h")

#include "Egg.xaml.g.h"

#else

namespace winrt::Farm::Animals::implementation
{
    template <typename D, typename ... I>
    using EggT = Egg_base<D, I ...>;
}

#endif
