// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "module.h"

namespace winrt {

namespace Farm::Animals::implementation {

template <typename D, typename ... I>
struct HenT
    : impl::module_lock, implements<D, Farm::Animals::IHen, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return hstring{ L"Farm.Animals.Hen" };
    }
};

template <typename D, typename T, typename ... I>
struct HenFactoryT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return hstring{ L"Farm.Animals.Hen" };
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

}
