// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "module.h"

namespace winrt {

namespace Farm::Animals::implementation {

template <typename D, typename ... I>
struct HenBase : impl::module_lock, implements<D, Farm::Animals::IHen, I ...>
{
    using class_type = Farm::Animals::Hen;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Hen";
    }
};

template <typename D, typename T, typename ... I>
struct HenFactoryBase : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Farm.Animals.Hen";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_HEN_X_H) || __has_include("Hen.x.h")

#include "Hen.x.h"

#else

template <typename D, typename ... I>
using HenT = HenBase<D, I ...>;

template <typename D, typename T, typename ... I>
using HenFactoryT = HenFactoryBase<D, T, I ...>;

#endif

}

}
