// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"
#include "Root.h"

namespace winrt::Composable::Base::implementation {

template <typename D, typename ... I>
struct Derived_base : implements<D, Composable::Base::implementation::Root, Composable::Base::IDerived, Composable::Base::IDerivedOverrides, composable, I ...>
{
    using class_type = Composable::Base::Derived;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Composable.Base.Derived";
    }
protected:
    using dispatch = impl::dispatch_to_super<D, Composable::Base::IDerivedOverrides, Composable::Base::IRootOverrides>;
    auto super() noexcept { return dispatch::super(static_cast<D&>(*this)); }
};

}

namespace winrt::Composable::Base::factory_implementation {

template <typename D, typename T, typename ... I>
struct DerivedT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Composable::Base::IDerivedFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Composable.Base.Derived";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Composable::Base::IDerived CreateInstance(Windows::Foundation::IInspectable const& outer, Windows::Foundation::IInspectable& inner)
    {
        return impl::composable_factory<T>::template CreateInstance<Composable::Base::IDerived>(outer, inner);
    }

    Composable::Base::IDerived CreateInstanceWithName(hstring const& name, Windows::Foundation::IInspectable const& outer, Windows::Foundation::IInspectable& inner)
    {
        return impl::composable_factory<T>::template CreateInstance<Composable::Base::IDerived>(outer, inner, name);
    }
};

}

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_DERIVED_XAML_G_H) || __has_include("Derived.xaml.g.h")

#include "Derived.xaml.g.h"

#else

namespace winrt::Composable::Base::implementation
{
    template <typename D, typename ... I>
    using DerivedT = Derived_base<D, I ...>;
}

#endif
