// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#include "pch.h"
#include "Derived.h"
#include "Root.h"

namespace winrt::impl
{
    namespace
    {
        std::atomic<uint32_t> s_module_lock{};
    }

    module_lock::module_lock()
    {
        ++s_module_lock;
    }

    module_lock::~module_lock()
    {
        --s_module_lock;
    }
}

using namespace winrt;

HRESULT __stdcall WINRT_CanUnloadNow()
{
    if (impl::s_module_lock)
    {
        return S_FALSE;
    }

    clear_factory_cache();
    return S_OK;
}

HRESULT __stdcall WINRT_GetActivationFactory(HSTRING classId, void** factory)
{
    try
    {
        *factory = nullptr;
        wchar_t const* const name = WindowsGetStringRawBuffer(classId, nullptr);

        if (0 == wcscmp(name, L"Composable.Base.Derived"))
        {
            *factory = detach_abi(make<Composable::Base::factory_implementation::Derived>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"Composable.Base.Root"))
        {
            *factory = detach_abi(make<Composable::Base::factory_implementation::Root>());
            return S_OK;
        }

        return hresult_class_not_available().to_abi();
    }
    catch (...)
    {
        return impl::to_hresult();
    }
}
