// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "module.h"

namespace winrt {

namespace Composable::Base::implementation {

template <typename D, typename ... I>
struct RootBase
    : impl::module_lock, implements<D, Composable::Base::IRoot, Composable::Base::IRootOverrides, composable, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Composable.Base.Root";
    }
protected:
    using dispatch = impl::dispatch_to_super<D, Composable::Base::IRootOverrides>;
    auto super() noexcept { return dispatch::super(static_cast<D&>(*this)); }
};

template <typename D, typename T, typename ... I>
struct RootFactoryBase : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Composable::Base::IRootFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Composable.Base.Root";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Composable::Base::IRoot CreateInstance(Windows::Foundation::IInspectable const& outer, Windows::Foundation::IInspectable& inner)
    {
        return impl::composable_factory<T>::template CreateInstance<Composable::Base::IRoot>(outer, inner);
    }
};

#if defined(WINRT_FORCE_INCLUDE_ROOT_X_H) || __has_include("Root.x.h")

#include "Root.x.h"

#else

template <typename D, typename ... I>
using RootT = RootBase<D, I ...>;

template <typename D, typename T, typename ... I>
using RootFactoryT = RootFactoryBase<D, T, I ...>;

#endif

}

}
