// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"
#include "winrt/Complex.Authoring.Composability.Open.h"

namespace winrt::Complex::Authoring::Composability::Open::implementation {

template <typename D, typename... I>
struct WINRT_EBO Base_base : impl::module_lock, implements<D, Complex::Authoring::Composability::Open::IBase, composable, I...>
{
    using class_type = Complex::Authoring::Composability::Open::Base;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename D::first_interface, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Composability.Open.Base";
    }
};

}

namespace winrt::Complex::Authoring::Composability::Open::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO BaseT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Complex::Authoring::Composability::Open::IBaseFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Composability.Open.Base";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Complex::Authoring::Composability::Open::IBase CreateInstance(Windows::Foundation::IInspectable const& outer, Windows::Foundation::IInspectable& inner)
    {
        return impl::composable_factory<T>::template CreateInstance<Complex::Authoring::Composability::Open::IBase>(outer, inner);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_BASE_XAML_G_H) || __has_include("Composability.Open.Base.xaml.g.h")

#include "Composability.Open.Base.xaml.g.h"

#else

namespace winrt::Complex::Authoring::Composability::Open::implementation
{
    template <typename D, typename... I>
    using BaseT = Base_base<D, I...>;
}

#endif
