// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"
#include "winrt/Complex.Authoring.Factory.h"

namespace winrt::Complex::Authoring::Factory::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO StaticFactoryT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Complex::Authoring::Factory::IStaticFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Factory.StaticFactory";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    void StaticMethod()
    {
        T::StaticMethod();
    }
};

}
