// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#include "pch.h"
#include "Bread.h"
#include "BreadBakedEventArgs.h"
#include "Oven.h"

namespace winrt::impl
{
    namespace
    {
        std::atomic<uint32_t> s_module_lock{};
    }

    module_lock::module_lock()
    {
        ++s_module_lock;
    }

    module_lock::~module_lock()
    {
        --s_module_lock;
    }
}

using namespace winrt;
using namespace Windows::Foundation;

HRESULT __stdcall DllCanUnloadNow()
{
    return impl::s_module_lock ? S_FALSE : S_OK;
}

HRESULT __stdcall DllGetActivationFactory(HSTRING classId, ::IUnknown** factory)
{
    try
    {
        wchar_t const* const name = WindowsGetStringRawBuffer(classId, nullptr);

        if (0 == wcscmp(name, L"Microsoft.SDKSamples.Kitchen.Bread"))
        {
            *factory = detach_abi(make<Microsoft::SDKSamples::Kitchen::implementation::BreadFactory>());
        }
        else if (0 == wcscmp(name, L"Microsoft.SDKSamples.Kitchen.BreadBakedEventArgs"))
        {
            *factory = detach_abi(make<Microsoft::SDKSamples::Kitchen::implementation::BreadBakedEventArgsFactory>());
        }
        else if (0 == wcscmp(name, L"Microsoft.SDKSamples.Kitchen.Oven"))
        {
            *factory = detach_abi(make<Microsoft::SDKSamples::Kitchen::implementation::OvenFactory>());
        }
        else
        {
            throw hresult_class_not_available();
        }

        return S_OK;
    }
    catch (...)
    {
        *factory = nullptr;
        return impl::to_hresult();
    }
}
