// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"

namespace winrt::Complex::Authoring::Factory::implementation {

template <typename D, typename ... I>
struct SimpleFactory_base : impl::module_lock, implements<D, Complex::Authoring::Factory::ISimpleFactory, I ...>
{
    using class_type = Complex::Authoring::Factory::SimpleFactory;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Factory.SimpleFactory";
    }
};

}

namespace winrt::Complex::Authoring::Factory::factory_implementation {

template <typename D, typename T, typename ... I>
struct SimpleFactoryT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Factory.SimpleFactory";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_SIMPLEFACTORY_XAML_G_H) || __has_include("Factory.SimpleFactory.xaml.g.h")

#include "Factory.SimpleFactory.xaml.g.h"

#else

namespace winrt::Complex::Authoring::Factory::implementation
{
    template <typename D, typename ... I>
    using SimpleFactoryT = SimpleFactory_base<D, I ...>;
}

#endif
