// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "module.h"

namespace winrt {

namespace Complex::Authoring::implementation {

template <typename D, typename ... I>
struct LanguageBase : impl::module_lock, implements<D, Complex::Authoring::ILanguage, I ...>
{
    using class_type = Complex::Authoring::Language;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Language";
    }
};

template <typename D, typename T, typename ... I>
struct LanguageFactoryBase : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Language";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_LANGUAGE_X_H) || __has_include("Language.x.h")

#include "Language.x.h"

#else

template <typename D, typename ... I>
using LanguageT = LanguageBase<D, I ...>;

template <typename D, typename T, typename ... I>
using LanguageFactoryT = LanguageFactoryBase<D, T, I ...>;

#endif

}

}
