// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "Complex.Authoring.h"

namespace winrt::impl {

struct module_lock
{
    module_lock();
    ~module_lock();
};

}
