// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.1.private

#pragma once

#include "winrt/Complex.Authoring.h"

#include "winrt/Complex.Authoring.Composability.Closed.h"

#include "winrt/Complex.Authoring.Composability.Open.h"

#include "winrt/Complex.Authoring.Factory.h"

#include "winrt/Complex.Authoring.Nested.h"

namespace winrt::impl {

struct module_lock
{
    module_lock();
    ~module_lock();
};

}
