// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"

namespace winrt::Complex::Authoring::factory_implementation {

template <typename D, typename T, typename ... I>
struct StaticT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, Complex::Authoring::IStatic, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Static";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    Windows::Foundation::Rect Bounds()
    {
        return T::Bounds();
    }
};

}
