// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"

namespace winrt::Complex::Authoring::implementation {

template <typename D, typename ... I>
struct Structs_base : impl::module_lock, implements<D, Complex::Authoring::IStructs, I ...>
{
    using class_type = Complex::Authoring::Structs;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Structs";
    }
};

}

namespace winrt::Complex::Authoring::factory_implementation {

template <typename D, typename T, typename ... I>
struct StructsT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Complex.Authoring.Structs";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_STRUCTS_XAML_G_H) || __has_include("Structs.xaml.g.h")

#include "Structs.xaml.g.h"

#else

namespace winrt::Complex::Authoring::implementation
{
    template <typename D, typename ... I>
    using StructsT = Structs_base<D, I ...>;
}

#endif
