#include <sdkddkver.h>

import "oaidl.idl";
import "ocidl.idl";

import "windows.foundation.idl";

namespace Modern.Test
{

[uuid(BCA23A6A-A66A-4834-98DD-9A3A49F88201)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFooStatics1 : IInspectable
{
    HRESULT Do();
}

[uuid(3137997F-C77E-4794-BA9A-23A269F75CFF)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo2 : IInspectable
{
    HRESULT Do();
}

[contract(Windows.Foundation.UniversalApiContract, 1)]
[static(IFooStatics1, Windows.Foundation.UniversalApiContract, 1)]
runtimeclass Bar1
{

}

[contract(Windows.Foundation.UniversalApiContract, 1)]
runtimeclass Bar2
{
    [default] interface IFoo2;
}

}