#include <sdkddkver.h>

import "oaidl.idl";
import "ocidl.idl";

import "windows.foundation.idl";

namespace Modern.Test1
{

[uuid(179DC05A-C39C-4B13-B23A-63A9AFBB9274)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do([out, retval] Windows.Foundation.IAsyncOperation<HSTRING>** result);
}

}

namespace Modern.Test2
{

[uuid(B5A35AF2-A86A-4D67-A9CF-CDEF4BA5C2B2)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do([out, retval] Windows.Foundation.IAsyncOperationWithProgress<UINT, UINT32>** operation);
}

}

namespace Modern.Test3
{

[uuid(FC36FFCA-29BC-42E6-BAF1-BF38C73ADD90)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do([out, retval] Windows.Foundation.IAsyncActionWithProgress<DOUBLE>** operation);
}

}

namespace Modern.Test4
{

[uuid(0DD79875-1399-4FAA-9C03-61B08463F5FD)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IVectorView<INT>* p);
}

}

namespace Modern.Test5
{

[uuid(1F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IVector<DOUBLE>* p);
}

}

namespace Modern.Test6
{

[uuid(2F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IIterable<UINT32>* p);
}

}

namespace Modern.Test7
{

[uuid(3F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IMap<HSTRING, HSTRING>* p);
}

}

namespace Modern.Test8
{

[uuid(4F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IMapView<INT, INT>* p);
}

}

namespace Modern.Test9
{

[uuid(5F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IObservableMap<DOUBLE, DOUBLE>* p);
}

}

namespace Modern.Test10
{

[uuid(6F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IObservableVector<FLOAT>* p);
}

}