#include <sdkddkver.h>

import "oaidl.idl";
import "ocidl.idl";

import "windows.foundation.idl";

// Verify that generic interfaces are reused because they were either previously parsed or implicity generated.

namespace Modern.Test1
{

[uuid(1F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IObservableVector<FLOAT>* p);
}

}

namespace Modern.Test2
{

[uuid(2F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo1 : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IObservableVector<FLOAT>* p);
}

[uuid(3F81FDB4-B758-4CBF-9E29-FADB9D33D172)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo2 : IInspectable
{
    HRESULT Do(Windows.Foundation.Collections.IObservableVector<IIterable<FLOAT>*>* p);
}

}