
#include <sdkddkver.h>

import "oaidl.idl";
import "ocidl.idl";

import "windows.foundation.idl";

namespace Modern.Test
{

runtimeclass Bar1;

[exclusiveto(Bar1)]
[uuid(9C6CD845-C9E7-45F5-947D-9CFADD47A1B1)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo0 : IInspectable
{
    HRESULT Do();
}

[uuid(35392C38-CDED-4D4C-9637-05F15C1C9406)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo1 : IInspectable
{
    HRESULT Do();
}

[uuid(ABDB6D60-F7F8-4B55-9838-C01EE92F5B69)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo2 : IInspectable
{
    HRESULT Do2();
}

runtimeclass Bar3;
runtimeclass Bar4;

[uuid(EEB85F0F-B4D5-4B9B-A799-8D4C2F25876B)]
[exclusiveto(Bar3)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo3 : IInspectable
{
    HRESULT CreateInstance([in] IInspectable* outer, [out] IInspectable** inner, [out, retval] Bar3** instance);
}

[uuid(D59225A2-020B-42A7-8FE4-A59D123B9A35)]
[exclusiveto(Bar4)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
interface IFoo4 : IInspectable
{
    HRESULT CreateInstance([in] IInspectable* outer, [out] IInspectable** inner, [out, retval] Bar4** instance);
}

// MIDL4066 : A member name has been qualified with an interface name because name collisions occurred across interface members on a runtime class. 
// "Do" has been renamed as "Modern.Test.IFoo1.Do" on runtime class "Modern.Test.Bar1"
midl_pragma warning(disable : 4066)
[activatable(Windows.Foundation.UniversalApiContract, 1)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
runtimeclass Bar1
{
    interface IFoo1;
    [default] interface IFoo2;
    interface IFoo0;
}
midl_pragma warning(default : 4066)

[contract(Windows.Foundation.UniversalApiContract, 1)]
runtimeclass Bar2
{
    [default] interface IFoo1;
    interface IFoo2;
}

[marshaling_behavior(agile)] // needed to get composable
[threading(both)] // needed to get composable
[composable(IFoo3, public, Windows.Foundation.UniversalApiContract, 1)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
runtimeclass Bar3
{
    [default] interface IFoo2;
}

[marshaling_behavior(agile)] // needed to get composable
[threading(both)] // needed to get composable
[composable(IFoo4, protected, Windows.Foundation.UniversalApiContract, 1)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
runtimeclass Bar4 : Bar3
{
    [default] interface IFoo2;
}

[deprecated("Awesome deprecated text", deprecate, Windows.Foundation.UniversalApiContract, 1)]
[contract(Windows.Foundation.UniversalApiContract, 1)]
runtimeclass BarDeprecated
{
    [default] interface IFoo2;
}

}