#include <sdkddkver.h>

import "oaidl.idl";
import "ocidl.idl";

import "windows.foundation.idl";

/*
create table Structures
(
	FullName,
	Name,
	Depends default 0
);

create table Fields
(
	Name,
	Type,
	StructureId
);
*/

namespace Modern.Test
{

[contract(Windows.Foundation.UniversalApiContract, 1)]
typedef struct Struct1
{
    UINT32 BytesRetrieved;
} Struct1;

[contract(Windows.Foundation.UniversalApiContract, 1)]
typedef struct Struct2
{
    BYTE byteField;
    INT16 int16Field;
    UINT16 uint16Field;
    INT32 int32Field;
    UINT32 uint32Field;
    INT64 int64Field;
    UINT64 uint64Field;
    FLOAT floatField;
    DOUBLE doubleField;
    boolean booleanField;
    WCHAR wcharField;
    HSTRING hstringField;
    Windows.Foundation.TimeSpan structField;
    Windows.Foundation.PropertyType enumField;
} Struct2;

[contract(Windows.Foundation.UniversalApiContract, 1)]
[deprecated("Awesome deprecated text", deprecate, Windows.Foundation.UniversalApiContract, 1)]
typedef struct DeprecatedStruct
{
    DWORD   Value;
} DeprecatedStruct;

}